export enum AiXpandCommandAction {
    ARCHIVE_CONFIG = 'ARCHIVE_CONFIG',
    ARCHIVE_CONFIG_ALL = 'ARCHIVE_CONFIG_ALL',
    DELETE_CONFIG_ALL = 'DELETE_CONFIG_ALL',
    UPDATE_CONFIG = 'UPDATE_CONFIG',
    UPDATE_PIPELINE_INSTANCE = 'UPDATE_PIPELINE_INSTANCE',
}
