export enum AiXpandCommandAction {
    ARCHIVE_CONFIG = 'ARCHIVE_CONFIG',
    ARCHIVE_CONFIG_ALL = 'ARCHIVE_CONFIG_ALL',
    BATCH_UPDATE_PIPELINE_INSTANCE = 'BATCH_UPDATE_PIPELINE_INSTANCE',
    DELETE_CONFIG_ALL = 'DELETE_CONFIG_ALL',
    PIPELINE_COMMAND = 'PIPELINE_COMMAND',
    UPDATE_CONFIG = 'UPDATE_CONFIG',
    UPDATE_PIPELINE_INSTANCE = 'UPDATE_PIPELINE_INSTANCE',
}
